myapp/urls.py
from django.urls import path
app_name="myapp"
from myapp import views
urlpatterns = [
    path('',views.home,name='home'),
    path('register/', views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
]

p29/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    password= forms.CharField(max_length=100, required=True,widget=forms.PasswordInput)
    class Meta:
        model= User
        fields=('username','password','email')

myapp/views.py
from django.shortcuts import render,redirect
from myapp.forms import RegistrationForm
from django.contrib.auth.models import User
# Create your views here.
def home(request):
    return render(request,"myapp/home.html")

def register(request):
    if request.method=='POST':
        form= RegistrationForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
        else:
            return render(request,"myapp/register.html", {'form':form})
    form=RegistrationForm()
    return render(request,"myapp/register.html", {'form':form})

from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
def user_login(request):
    if request.method=="POST":
        username=request.POST.get("uname")
        pwd= request.POST.get('pwd')
        user= authenticate(request,username=username,password=pwd)
        if user.is_active:
            login(request,user)
            return redirect('myapp:home')
        else:
            return redirect('myapp:home')
    return render(request,'myapp/user_login.html')
@login_required
def user_logout(request):
    logout(request)
    return redirect('myapp:home')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% block title %}
    <title>BasePage</title>
    {% endblock %}
</head>
<body>
    {% include "partials/_navbar.html" %}
    {% block content %}
    <div class="jumbotron">
        <h1>BASE HTML</h1> 
    </div>
   {% endblock %}
</body>
</html>

templates/myapp/home.html
{% extends 'base.html' %}
{% block title %}
    <title>HomePage</title>
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1>HOME HTML</h1> 
        {% if user.is_authenticated %}
        <h2>Welcome Mr./Ms. {{user.username}}</h2>
        {% endif %}
    </div>
{% endblock %}

templates/myapp/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>RegisterPage</title>
{% endblock %}
{% block content %}
    <h1>For Registering..Fill the form....</h1>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Register" class="btn btn-primary">
    </form>
{% endblock %}

templates/myapp/user_login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    <title>Login Page</title>
{% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleInputEmail">UserName</label>
        <input type="text" class="form-control" name="uname" id="exampleInputEmail" aria-describedby="emailHelp">
        <small id="emailHelp" class="form-text text-muted">We'll never share email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" name="pwd" id="exampleInputPassword1">
    </div>
    <input type="submit" value="Login" class="btn btn-primary">
</form>
{% endblock %}

templates/partials/_navbar.html
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'myapp:home' %}">Home</a> 
    </li> 
    <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:register' %}">Register</a>
    </li>
    <li class="nav-item">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'myapp:user_logout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'myapp:user_login' %}">Login</a>
        {% endif %}
    </li>
</ul>